### ISSUE TITLE
依存モジュールをまとめてインストールできる方法を追加

### ISSUE THREAD

**Issue by matthew70** [hiroki8080/Kokemomo#19]
`Kokemomo`をサーバーにデプロイする際、依存モジュールを一括でインストールできたら良いなと思いました。
方法としては、`pip`でよく使われる`requirements.txt`を用意するのはどうでしょうか？
`requirements.txt`に依存モジュールを記載しておくと`pip install -r requirements.txt`でモジュールを一括インストールすることが可能です。

また、例えばHerokuは`git push`時に`requirements.txt`の内容を自動でインストールしてくれるようです。

開発フェーズ時には`requirements.txt`が向いているように感じますが、いくつか[議論](http://ja.stackoverflow.com/questions/209/requirements-txt-%E3%81%A8-setuptools-%E3%81%AE-install-requires-%E3%81%AF-%E3%81%A9%E3%81%A1%E3%82%89%E3%82%92%E4%BD%BF%E3%81%86%E3%81%B9%E3%81%8D%E3%81%A7%E3%81%99%E3%81%8B) もあるようでした。

### `requirements.txt`を使うときのTODO

- [x] `requirements.txt`を用意
- [x] `pip install -r requirements.tx`でインストールできることをドキュメントに記載

**Comment by hiroki8080** [comment]
pip install -r requirements.txtでインストールできるのは良いですね！
今のところ手動でインストールしているので、是非追加をお願いします！
