### ISSUE TITLE
Herokuですぐ動くように調整する

### ISSUE THREAD

**Issue by matthew70** [hiroki8080/Kokemomo#21]

**Comment by matthew70** [comment]
急ぎではないです。メモ的に書いておきます。

HerokuをPlugin化することを考えてみたのですが、ディレクトリトップにProcfileを置かなければいけないと思うのでPluginという形は厳しいのかもしれません。Pluginインストール時にファイルを生成することができれば別かもですが:astonished:

そこで一案ですが、`git subtree`あたりを使う方法はどうでしょう。いっその事heroku-kokemomoというリポジトリを作りProcfileなどを設置し、アプリケーションとなるKokemomoはheroku-kokemomoディレクトリ下に`git subtree`で加える方法です。

**Comment by hiroki8080** [comment]
プラグインの件、了解です。
git subtree良いですね！私もその構成が良いと思います。
あと、heroku限定というより、もう少し抽象的なリポジトリが良いかもです。
例えば環境構築用とかですね。

**Comment by matthew70** [comment]
保留状態なので一旦クローズします:bow:
